---
# HORIZONTAL POD AUTOSCALER
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: votingapp-hpa
  namespace: titan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votingapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
