apiVersion: v2
name: titan
description: A helm chart for the titan app microservice.
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: prereqs
    repository: file://charts/prereqs
    version: 0.0.1
    condition: prereqs.enabled
  - name: votinganalytics
    repository: file://charts/votinganalytics
    version: 0.0.1
    condition: votinganalytics.enabled
  - name: votingapp
    repository: file://charts/votingapp
    version: 0.0.1
    condition: votingapp.enabled
